project:
  type: book
  output-dir: docs/

book:
  title: "Colours of the Taylor Swift Universe"
  author: "Marina Ferrari de Aquino Klemm & Charlotte Jones-Todd"
  date: ""
  chapters:
    - index.qmd
    - data.qmd
    - viz.qmd
    - outfit_transitions.qmd
    - colour_sentiments.qmd
    - lyric_sentiments.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



